import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname } from 'node:path'
import { test } from 'node:test'
import ts from 'typescript'

const require = createRequire(import.meta.url)
const React = require('react')
const { renderToStaticMarkup } = require('react-dom/server')
const { QRCodeSVG } = require('qrcode.react')
const sharp = require(
  require.resolve('sharp', { paths: [dirname(require.resolve('next/package.json'))] })
)
const { RGBLuminanceSource, BinaryBitmap, HybridBinarizer, QRCodeReader } = require(
  require.resolve('@zxing/library', { paths: [dirname(require.resolve('@zxing/browser'))] })
)
const module = { exports: {} }
const code = ts.transpileModule(
  readFileSync(new URL('../../lib/athlete-identity.ts', import.meta.url), 'utf8'),
  {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS },
  }
).outputText
new Function('exports', 'module', code)(module.exports, module)
const { credentialQrValue, parseCredentialQr } = module.exports

test('credential QR generated by the UI library is decoded by the camera library', async () => {
  const token = 'a'.repeat(64)
  const value = credentialQrValue(token)
  const svg = renderToStaticMarkup(
    React.createElement(QRCodeSVG, {
      value,
      size: 216,
      level: 'M',
      marginSize: 4,
    })
  )
  const { data, info } = await sharp(Buffer.from(svg))
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const pixels = new Int32Array(info.width * info.height)
  for (let i = 0; i < pixels.length; i++) {
    pixels[i] = (data[i * 3] << 16) | (data[i * 3 + 1] << 8) | data[i * 3 + 2]
  }
  const bitmap = new BinaryBitmap(
    new HybridBinarizer(new RGBLuminanceSource(pixels, info.width, info.height))
  )
  const decoded = new QRCodeReader().decode(bitmap).getText()
  assert.equal(decoded, value)
  assert.equal(parseCredentialQr(decoded), token)
})
